spring.application.name=demo

# ── Database Configuration ──────────────────────────────────────
spring.datasource.url=jdbc:postgresql://localhost:5433/med_sutra_ai
spring.datasource.username=postgres
spring.datasource.password=Bankai

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ── JWT Configuration ──────────────────────────────────────
jwt.secret=dGhpc0lzQVZlcnlTZWN1cmVTZWNyZXRLZXlGb3JTbWFydE1lZFN1dHJheerhtrhew4hh5yhsreQXBwMjAyNg==
jwt.expiration=86400000

# ── OpenWeatherMap API ─────────────────────────────────────
weather.api.key=504116dd8a3c4521bf9174805262704